name: supa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  fl_chart: ^0.69.0
  image_picker: ^1.0.7
  lottie: ^3.3.2
  supabase_flutter: ^2.12.0
  google_fonts: ^8.0.0
  cached_network_image: ^3.4.1
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/animations/
    - assets/translations/en.json
    - assets/translations/ru.json
    - assets/translations/tm.json
